# Generated by Django 5.0.6 on 2024-06-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Listings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "condition",
                    models.CharField(
                        choices=[("used", "Used"), ("new", "New")],
                        default="used",
                        max_length=50,
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("bike", "Bike"),
                            ("parts", "Parts"),
                            ("models", "Models"),
                            ("others", "Others"),
                        ],
                        default="others",
                        max_length=50,
                    ),
                ),
                (
                    "sale_type",
                    models.CharField(
                        choices=[
                            ("Available for pickup", "Pick Up"),
                            ("Available for shipping", "Ship"),
                        ],
                        default="Available for pickup",
                        max_length=50,
                    ),
                ),
                ("price", models.FloatField()),
                ("address", models.CharField(max_length=100)),
                ("main_photo", models.ImageField(upload_to="")),
                ("photo_1", models.ImageField(blank=True, upload_to="")),
                ("list_date", models.DateField(auto_now_add=True)),
                ("contact_email", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "Listings",
            },
        ),
    ]
